name: single_cell
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - scanpy
  - anndata
  - leidenalg
  - python-igraph
  - umap-learn
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - scipy
  - jupyterlab
  - ipykernel
  - nbformat
  - nbconvert
  - pip
  - pip:
      - pertpy
